### PR TITLE
Fix for running composer locally

### PR DESCRIPTION
**Pull request by cicalese**
If composer is run locally in the extension directory, be sure that the files for the extension get autoloaded.

### CODE REVIEW

**Comment by mwjames** [comment]
> If composer is run locally in the extension directory, be sure that the files for the extension get autoloaded.

When and why would this extension be loaded locally? The standard deployment  is to use SMW which when loaded via Composer is expected (SMW can be loaded locally but this has historic reasons such as 1.19 etc) to use the standard vendor location found in the MW root.

**Comment by cicalese** [comment]
I was asked to create a MediaWiki-vagrant role for SMW. This is used primarily for experimentation and development. I thought it would also be useful to create MediaWiki-vagrant roles for some helpful companion extensions to SMW. The composer installation approach for extensions in MediaWiki-vagrant is to run composer in the extension directories, not at the root directory. With this simple fix, running composer in the extension directories works great - again, primarily for experimentation and development. Modifying MediaWiki-vagrant to run composer in the root directory for extensions would be a considerably more complicated endeavor for a variety of reasons. So, this work allows a broad community of folks to easily gain exposure to the SMW suite of extensions in an experimental environment.

Cindy



Sent with Good (www.good.com)
________________________________

**Comment by mwjames** [comment]
> I was asked to create a MediaWiki-vagrant role for SMW. This is used primarily for experimentation and development. I thought it would also be useful to create MediaWiki-vagrant roles for some helpful companion extensions to SMW.

This context makes more sense now but could I end up having different SMW installations within the same vagrant setup? 

Being the devils advocate, could it potentially mean that you install SMW with 2.3 but SESP 1.4 (which would hypothetically require 2.4) would then install SMW 2.4 locally so that suddenly I have two installations with different requirements because the management is done locally instead of being centralized from MW root?

**Comment by cicalese** [comment]
Yes, absolutely, you could have different versions. MediaWiki-vagrant is intended to use only master [0]. But, if you enable roles at different times, they could pull in different commits of SMW from master. This could be remedied by running "composer update" for each extension, right? This is definitely not an ideal situation, but, as stated above, this is intended as an experimentation environment. 

[0] https://www.mediawiki.org/wiki/MediaWiki-Vagrant#How_do_I....3F

**Comment by mwjames** [comment]
> Yes, absolutely, you could have different versions. MediaWiki-vagrant is intended to use only master [0]. But, if you enable roles at different times, they could pull in different commits of SMW from master. 

Is there a way to check whether this is being a Vagrant client or not? Because this could open up (without noticing that classes are loaded from the local vendor instead of the "global") the confusion for regular installers who might run composer install/update (by accident) from a local client and then get confused when the "global" version requires (such as locally uses SMW 2.3 but MW root contains 2.4+) an update but the local still contains an outdated reference.

@JeroenDeDauw @kghbln Seeking some input here whether this can increase the installation hurdle or not.

**Comment by cicalese** [comment]
Good question. I will research whether there is a way to tell at run time that this is running within a MediaWiki-vagrant environment.

**Comment by cicalese** [comment]
If there is not a way to tell, the extensions could introduce a Boolean variable that would default to the "global" behavior that I would toggle to "local" by setting the variable in the MediaWiki-vagrant role definition. Extension roles can include configuration variables.

**Comment by cicalese** [comment]
I have not yet found a way to determine at run time that the extension is running in a MediaWiki-vagrant instance. But, the more I think about it, the more I believe that a variable in the extensions to dictate whether or not to autoload locally would be best. There might be other environments that could benefit from that behavior, and it seems risky to tie the autoloading behavior to something MediaWiki-vagrant-specific that could change or not be generalizable.

**Comment by JeroenDeDauw** [comment]
There is stuff like this in other SMW related extensions. I think on itself it does not hurt, as long as we don't recommend people to use this, as it indeed does have the mentioned issues.

**Comment by cicalese** [comment]
Thank you!

**Pull request merged**
