### PR TITLE
Add new property PageImage

### PR DESCRIPTION
**Pull request by harugon**
This PR addresses or contains:
- Adds support for ```__PAGEIMG``` PageImage (Extensions:PageImage)

This PR includes:
- [x] Tests (unit/integration)
- [ ] CI build passed

### CODE REVIEW

**Comment by gesinn-it-gea** [comment]
@harugon thanks for your contribution. Please also add `qqq.json`.

**Comment by harugon** [comment]
@gesinn-it-gea  Thank you so much for guidance.
 add ```qqq.json```

**Comment by gesinn-it-gea** [comment]
@harugon would be cool if you could have a look at the other failing tests and ideally fix them so we get some green lights from CI.

**Comment by harugon** [comment]
- Fix wrong   NamespacePropertyAnnotator (param  $namespace)
- Fix  Tests (full namespaced name)

**Comment by harugon** [comment]
@gesinn-it-gea 
Fix  
- NamespaceProperty
- test full namespaced(@covers)

**Pull request closed without merging**
