### PR TITLE
Fix for issue 49

### PR DESCRIPTION
**Pull request by kghbln**
Make sure that _USEREDITCNT is only applied to user pages and not user's subpages. Thanks go to MWJames for the fix.

### CODE REVIEW

**Comment by kghbln** [comment]
So this fails due to the "composer-merge-plugin" O_o

**Comment by mwjames** [comment]
I tried to fix Travis but apparently WMF just screws around, I'm so done with this s....

[0] https://phabricator.wikimedia.org/T106148

**Comment by mwjames** [comment]
Someone can follow-up on this issue encountered with master, I don't have to time to entertain those blokes. 

@kghbln You are good to go.

**Comment by kghbln** [comment]
Master disaster - a rhyme I do not really like. Seem to be the way it si. Thanks for your help!

**Pull request merged**
