### PR TITLE
Add user edit count to user pages

### PR DESCRIPTION
**Pull request by kghbln**
Addresses issue https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/issues/43 Thanks go to MWJames for the ultimate clue on how to do this.

### CODE REVIEW

**Comment by mwjames** [comment]
> Addresses issue #43

+1 

> The integration tests probably fail for an unrelated reason since even the edit to the RELEASE-NOTES fail.

OK, the tests didn't pass because of (the new `_USEREDITCNT` adds a +1 count):

```
..................................................F...........  63 / 108 ( 58%)
.............................................
Time: 5.27 seconds, Memory: 35.50Mb
There was 1 failure:
1) SESP\Tests\PropertyRegistryTest::testRegisterAsFixedTablesWithNonExifProperties
Failed asserting that actual size 13 matches expected size 14.
```
> Admittedly I do not really know how to adapt the tests to include this.

If you add your added `_USEREDITCNT` to the `'sespSpecialProperties'` section of the [0] test, you should be ready to pass it.

https://github.com/SemanticMediaWiki/SemanticExtraSpecialProperties/blob/master/tests/phpunit/Unit/PropertyRegistryTest.php#L134

**Comment by kghbln** [comment]
Thanks a ton! That's what tests a for! Just add this one, so toi, toi, toi

**Comment by mwjames** [comment]
Test are all green :+1: 

@JeroenDeDauw Karsten has been picked to receive the developer honor badge

**Comment by JeroenDeDauw** [comment]
The badge will be delivard shortly

`_USEREDITCNT` - why not `_USER_EDIT_COUNT`?

**Comment by kghbln** [comment]
Great, that it now worked out. :)

> `_USEREDITCNT` - why not `_USER_EDIT_COUNT`?

For consistency since the other 13 follow this scheme.

> Karsten has been picked to receive the developer honor badge

I still believe that you have done most if not all of the brain work here.

**Comment by JeroenDeDauw** [comment]
I am please to hand over the prestigious certificate of official developer fluffiness to @kghbln!

dev

**Comment by kghbln** [comment]
Thank you, that's so kind.

**Pull request merged**
