### PR TITLE
Define DB_SLAVE for backwards compatibity

### LINKED ISSUE #124: MW 1.34+ Use of undefined constant DB_SLAVE - assumed 'DB_SLAVE'
### Setup and configuration

- MediaWiki | 1.34.0-rc.0 (366bf66)22:03, 15 October 2019
- PHP | 7.2.19-0ubuntu0.18.04.2 (apache2handler)
- MariaDB | 10.1.41-MariaDB-0ubuntu0.18.04.1
- Semantic MediaWiki | 3.2.0-alpha (c0b7a8f) 17:35, 14 October 2019
- Semantic Extra Special Properties | 2.1.0-alpha (9606083) 07:37, 10 September 2019

### Issue
When trying to run "rebuildElasticIndex.php" I get the following error:
```
Use of undefined constant DB_SLAVE - assumed 'DB_SLAVE' (this will throw an Error in a future version of PHP) in /../w/extensions/SemanticExtraSpecialProperties/src/AppFactory.php on line 75

Warning: Use of undefined constant DB_SLAVE - assumed 'DB_SLAVE' (this will throw an Error in a future version of PHP) in /../w/extensions/SemanticExtraSpecialProperties/src/AppFactory.php on line 75
UnexpectedValueException from line 462 of /../w/includes/libs/rdbms/loadbalancer/LoadBalancer.php: Invalid server index index #DB_SLAVE
```
Probably this is killing Elasticsearch replication for the whole wiki.

### Backtrace
```
#0 /../w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(896): Wikimedia\Rdbms\LoadBalancer->getConnectionIndex('DB_SLAVE', Array, 'DB9907120150926...')
#1 /../w/includes/libs/rdbms/loadbalancer/LoadBalancer.php(1043): Wikimedia\Rdbms\LoadBalancer->getConnection('DB_SLAVE', Array, 'DB9907120150926...', 0)
#2 /../w/includes/GlobalFunctions.php(2576): Wikimedia\Rdbms\LoadBalancer->getMaintenanceConnectionRef('DB_SLAVE', Array, 'DB9907120150926...')
#3 /../w/extensions/SemanticExtraSpecialProperties/src/AppFactory.php(75): wfGetDB('DB_SLAVE')
#4 /../w/extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/PageNumRevisionPropertyAnnotator.php(76): SESP\AppFactory->getConnection()
#5 /../w/extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/PageNumRevisionPropertyAnnotator.php(61): SESP\PropertyAnnotators\PageNumRevisionPropertyAnnotator->getPageRevisions(0)
#6 /../w/extensions/SemanticExtraSpecialProperties/src/PropertyAnnotators/DispatchingPropertyAnnotator.php(73): SESP\PropertyAnnotators\PageNumRevisionPropertyAnnotator->addAnnotation(Object(SMW\DIProperty), Object(SMW\SQLStore\EntityStore\StubSemanticData))
#7 /../w/extensions/SemanticExtraSpecialProperties/src/ExtraPropertyAnnotator.php(72): SESP\PropertyAnnotators\DispatchingPropertyAnnotator->addAnnotation(Object(SMW\DIProperty), Object(SMW\SQLStore\EntityStore\StubSemanticData))
#8 /../w/extensions/SemanticExtraSpecialProperties/src/HookRegistry.php(176): SESP\ExtraPropertyAnnotator->addAnnotation(Object(SMW\SQLStore\EntityStore\StubSemanticData))
#9 /../w/includes/Hooks.php(174): SESP\HookRegistry->SESP\{closure}(Object(SMW\SQLStore\SQLStore), Object(SMW\SQLStore\EntityStore\StubSemanticData))
#10 /../w/includes/Hooks.php(202): Hooks::callHook('SMWStore::updat...', Array, Array, NULL)
#11 /../w/extensions/SemanticMediaWiki/src/Store.php(234): Hooks::run('SMWStore::updat...', Array)
#12 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/FileIndexer.php(409): SMW\Store->updateData(Object(SMW\SQLStore\EntityStore\StubSemanticData))
#13 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(349): SMW\Elastic\Indexer\FileIndexer->SMW\Elastic\Indexer\{closure}()
#14 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(247): SMW\MediaWiki\Deferred\CallableUpdate->runUpdate()
#15 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/TransactionalCallableUpdate.php(168): SMW\MediaWiki\Deferred\CallableUpdate->doUpdate()
#16 /../w/extensions/SemanticMediaWiki/src/MediaWiki/Deferred/CallableUpdate.php(285): SMW\MediaWiki\Deferred\TransactionalCallableUpdate->doUpdate()
#17 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/FileIndexer.php(418): SMW\MediaWiki\Deferred\CallableUpdate->pushUpdate()
#18 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/FileIndexer.php(305): SMW\Elastic\Indexer\FileIndexer->addAnnotation(Object(SMW\SQLStore\SQLStore), Object(SMW\DIWikiPage))
#19 /../w/extensions/SemanticMediaWiki/src/Elastic/Indexer/Rebuilder.php(292): SMW\Elastic\Indexer\FileIndexer->index(Object(SMW\DIWikiPage), Object(ForeignAPIFile))
#20 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(378): SMW\Elastic\Indexer\Rebuilder->rebuild('755', Object(SMW\SQLStore\EntityStore\StubSemanticData))
#21 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(335): SMW\Maintenance\RebuildElasticIndex->rebuild_row('755', Object(stdClass), '183447', false)
#22 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(163): SMW\Maintenance\RebuildElasticIndex->rebuild()
#23 /../w/maintenance/doMaintenance.php(99): SMW\Maintenance\RebuildElasticIndex->execute()
#24 /../w/extensions/SemanticMediaWiki/maintenance/rebuildElasticIndex.php(437): require_once('/var/www/html/s...')
#25 {main}
```

### PR DESCRIPTION
**Pull request by kghbln**
This PR is made in reference to: #124 

This PR addresses or contains:
- Define DB_SLAVE for backwards compatibity as suggested by @JeroenDeDauw 

This PR includes:
- [ ] Tests (unit/integration)
- [ ] CI build passed

Fixes #124

### CODE REVIEW

**Comment by kghbln** [comment]
@JeroenDeDauw I made an educated guess as to where to add this actually. If fluff this can be squashed and merged. Will also do code changes to other extensions, too.

**Comment by kghbln** [comment]
@JeroenDeDauw This does not solve the issue. :( Now I am getting:

```
PHP Warning:  Use of undefined constant DB_SLAVE - assumed 'DB_SLAVE' (this will throw an Error in a future version of PHP) in /../w/extensions/SemanticExtraSpecialProperties/SemanticExtraSpecialProperties.php on line 27
Job queue is empty.
```

**Comment by kghbln** [comment]
Actually it is even worse now, because now I get this every time runJobs.php is run.

**Comment by kghbln** [comment]
Such a wast of time.

**Comment by kghbln** [comment]
And what really pisses me off is that I am getting this even though this extension is not even invoked. This is unbelievable.

**Comment by kghbln** [comment]
Another ten minutes of wasted time. This is becoming hilarious.

**Comment by kghbln** [comment]
Sadly I cannot fix this shit.

**Comment by JeroenDeDauw** [comment]
Presumably MW has not defined its constants by that point. Could try putting the snippet into initExtension in the same file.

Though to be honest I'm wondering what is in it for us to clean up the mess created by core devs? We are not running this version of MW anyway right? So... not our problem?

If we clean up the mess the whole time anyway then from core dev perspective why should they not continue like they are? If a bunch of users complain I know where to send them.

**Comment by kghbln** [comment]
This only fixed the notifications with the job queue but not the issue itself. PHP still claims an undefined constant. I am really surprised that it is not possible to define a constant easily in PHP. If I would be a programmer I would try to fix it, but I am not. I really depend on this. I am now just at 30 minutes which slipped into the void.

**Pull request merged**
