### PR TITLE
Add ability to track information from ApprovedRevisions

### LINKED ISSUE #94: Add Special Property to track ApprovedRevisions info
Client has requested the ability to do this and I've come up with something workable.

### PR DESCRIPTION
**Pull request by hexmode**
I'm not sure this is correct because there is no way to query if a page is covered by AR but has no  approved revision.  I could set the property to 0 in that case, which would expose the info, but is that the right thing to do?

Fixes #94

### CODE REVIEW

**Comment by s7eph4n** [comment]
Hmm, the test fails:
```
1) SESP\Tests\PropertyAnnotators\ApprovedRevPropertyAnnotatorTest::testAddAnnotation
Expectation failed for method name is equal to <string:getSubject> when invoked 1 time(s).
Method was expected to be called 1 times, actually called 0 times.
```
(https://travis-ci.org/SemanticMediaWiki/SemanticExtraSpecialProperties/builds/310588582)

**Comment by hexmode** [comment]
I can't reproduce this failure.  I get another one in an un-related part of code, but not this one.

Any tips on reproducing this?  I've tried to reproduce the php, etc versions but still no luck.

**Comment by mwjames** [comment]
> I can't reproduce this failure. I get another one in an un-related part of code, but not this one.

If you have `ApprovedRevs` installed then you won't get the error because the mock executes the expected part.

> Any tips on

I'd say looks good with the only exception that since we don't have and know what `ApprovedRevs` does we need to isolate this part (and would couldn't mocked even if we want it to since it relies on a static). I propose you change it to something like (where the ID can be tested):

```
@@ -4,11 +4,10 @@ namespace SESP\PropertyAnnotators;
 
 use SMW\DIProperty;
 use SMW\SemanticData;
 use SMWDataItem as DataItem;
 use SMWDINumber as DINumber;
-use SMWDIBoolean as DIBool;
 use SESP\PropertyAnnotator;
 use SESP\AppFactory;
 use ApprovedRevs;
 
 /**
@@ -28,36 +27,50 @@ class ApprovedRevPropertyAnnotator implements PropertyAnnotator {
 	 * @var AppFactory
 	 */
 	private $appFactory;
 
 	/**
+	 * @var Integer|null
+	 */
+	private $approvedRev;
+
+	/**
 	 * @param AppFactory $appFactory
 	 */
 	public function __construct( AppFactory $appFactory ) {
 		$this->appFactory = $appFactory;
 	}
 
 	/**
+	 * @since 2.0
+	 *
+	 * @param Integer $approvedRev
+	 */
+	public function setApprovedRev( $approvedRev ) {
+		$this->approvedRev = $approvedRev;
+	}
+
+	/**
 	 * {@inheritDoc}
 	 */
 	public function isAnnotatorFor( DIProperty $property ) {
 		return $property->getKey() === self::PROP_ID;
 	}
 
 	/**
 	 * {@inheritDoc}
 	 */
 	public function addAnnotation( DIProperty $property, SemanticData $semanticData ) {
-		if ( !class_exists( 'ApprovedRevs' ) ) {
-			return null;
-		}
 
-		$title = $semanticData->getSubject()->getTitle();
-		$rev = ApprovedRevs::getApprovedRevID( $title );
+		if ( $this->approvedRev === null && class_exists( 'ApprovedRevs' ) ) {
+			$this->approvedRev = ApprovedRevs::getApprovedRevID(
+				$semanticData->getSubject()->getTitle()
+			);
+		}
 
-		if ( is_numeric( $rev ) ) {
-			$semanticData->addPropertyObjectValue( $property, new DINumber( $rev ) );
+		if ( is_numeric( $this->approvedRev ) ) {
+			$semanticData->addPropertyObjectValue( $property, new DINumber( $this->approvedRev ) );
 		} else {
 			$semanticData->removeProperty( $property );
 		}
 	}
 }


```
... and adjust the test accordingly (+ test the removal).

```
@@ -3,10 +3,11 @@
 namespace SESP\Tests\PropertyAnnotators;
 
 use SESP\PropertyAnnotators\ApprovedRevPropertyAnnotator;
 use SMW\DIProperty;
 use SMW\DIWikiPage;
+use SMWDINumber as DINumber;
 
 /**
  * @covers \SESP\PropertyAnnotators\ApprovedRevPropertyAnnotator
  * @group semantic-extra-special-properties
  *
@@ -49,22 +50,44 @@ class ApprovedRevPropertyAnnotatorTest extends \PHPUnit_Framework_TestCase {
 		);
 	}
 
 	public function testAddAnnotation() {
 
-		$subject = DIWikiPage::newFromText( __METHOD__ );
+		$semanticData = $this->getMockBuilder( '\SMW\SemanticData' )
+			->disableOriginalConstructor()
+			->getMock();
+
+		$semanticData->expects( $this->once() )
+			->method( 'addPropertyObjectValue' )
+			->with(
+				$this->equalTo( $this->property ),
+				$this->equalTo( new DINumber( 42 ) ) );
+
+		$instance = new ApprovedRevPropertyAnnotator(
+			$this->appFactory
+		);
+
+		$instance->setApprovedRev( 42 );
+
+		$instance->addAnnotation( $this->property, $semanticData );
+	}
+
+	public function testRemoval() {
 
 		$semanticData = $this->getMockBuilder( '\SMW\SemanticData' )
 			->disableOriginalConstructor()
 			->getMock();
 
 		$semanticData->expects( $this->once() )
-			->method( 'getSubject' )
-			->will( $this->returnValue( $subject ) );
+			->method( 'removeProperty' )
+			->with( $this->equalTo( $this->property ) );
 
 		$instance = new ApprovedRevPropertyAnnotator(
 			$this->appFactory
 		);
 
+		$instance->setApprovedRev( false );
+
 		$instance->addAnnotation( $this->property, $semanticData );
 	}
+
 }
```

>  if a page is covered by AR but has no approved revision. I could set the property to 0 in that case, which would expose the info, but is that the right thing to do?

I suppose that if no approved rev is available it returns a non numeric value therefore removing any `___APPROVED` property annotation should be the correct approach.

**Comment by mwjames** [comment]
@hexmode Did you read the above comments?

**Comment by hexmode** [comment]
Sorry this has taken so long to come back to.  I started to add more information from AR, but decided to finish the small thing first.

**Comment by mwjames** [comment]
I'll have a look at it during the weekend.

**Comment by mwjames** [comment]
>  Add additional properties for AR 55722e8 

Do you think you can go back to 38efb19 which passes the tests and could merged fairly quick. Your new additions suffer from some design issues and I'd like to separate them to avoid dragging this PR.

Once the PR is merged, you should create a new PR with your additions. One definite issue in 55722e8 is  without having looked in too much detail the `LogReader` kitchen sink class which is created (instead of being injected) and uses access to `$dbr = wfGetDB( DB_SLAVE );` which is very hard to test.

The `AppFactory` should contain a `newLogReader`(better call it `DatabaseLogReader` as it is more precise on what the class does) and create an instance of the class (separation of concerns, single responsibility principle and so on ...).

**Comment by hexmode** [comment]
Thanks for the suggestions.  I'll work on a new pull request next week

**Comment by mwjames** [comment]
> Thanks for the suggestions. I'll work on a new pull request next week.

I know it can be a bit more work to think around on how to inject an object instead of just doing `$dbr = wfGetDB( DB_SLAVE );` but that sentiment is responsible why the MediaWiki code base looks like patchwork of different janitors trying to fix an issue instead of following some simple principles like inject an object instance, write a unit test that tests the case at hand and not the whole system, narrow interface instead of GOD classes and so on.

I'm not implying that this extension is any better (or for that matter SMW) but it takes a dedicated effort (#75) to not fall trap to the let's just fixed paradigm.

**Pull request merged**
