### PR TITLE
Add new property User edit count per namespace

### PR DESCRIPTION
**Pull request by alex-mashin**
Property type: record (formally page).
Property ID: '___USEREDITCNTNS'.
Property structure:
* '___USEREDITCNTNS_NS': _num (namespace number),
* '___USEREDITCNTNS_CNT': _num (user's edit count in this namespace).
Property domain: User namespace.
Property uniqueness: one value per namespace provided user has made edits in it.
Property annotator class: UserEditCountPropertyAnnotator.
Property annotator test class: UserEditCountPerNsPropertyAnnotatorTest.

{{#ask:}} query examples:

Edit count rating per user per namespace:
{{#ask:[[-User edit count per namespace::+]]
| mainlabel = -
| ? -User edit count per namespace
| ? Namespace
| ? Edit count
| sort = Edit count
| order = DESC
}}

Certain user's edits in the main namespace:
{{#ask:[[-User edit count per namespace::User:Alex Mashin]]
[[Namespace::0]]
| ? Edit count =
| mainlabel = -
}}

Made in reference to #169.

### CODE REVIEW

**Comment by gesinn-it** [comment]
@alex-mashin thanks for your contributions! I'm not so deep in SESP that I can approve. @JeroenDeDauw @hexmode can you have a look at this PR?

@alex-mashin I think it would help, if we get CI and Coverage back for SESP. Would you volunteer to add GitHub Actions and Codecov? Take a look at my recent contributions to SemanticResultFormats. It should be easy to apply it for SESP. This should preferably happen in a separate PR.

**Comment by alex-mashin** [comment]
> @alex-mashin I think it would help, if we get CI and Coverage back for SESP.
I have added a meaningful test for the new property "Edit count per namespace" and made sure it succeeds. I have also corrected a couple of obvious errors in other tests. However, being an amateur, my skills are not sufficient to repair the tests that have been broken for some time. 

> Would you volunteer to add GitHub Actions and Codecov?
I have no experience in this area.

**Comment by alex-mashin** [comment]
Could someone actually review the pull request?

**Comment by alex-mashin** [comment]
Anybody here?

**Comment by gesinn-it-gea** [comment]
@alex-mashin in the meanwhile I fixed CI. Can you please rebase your PR to run it against CI. Then it becomes more likely, that someone, who is familiar with this extension can do the review. Side note: all contributors are volunteers. At the moment a lot of the available time is probably bound to release SMW 4. Ping @JeroenDeDauw @hexmode

**Comment by alex-mashin** [comment]
> Can you please rebase your PR to run it against CI.
@gesinn-it-gea, rebase on what? I cannot see any recently merged pull requests in the master branch of this repository, or any recent changes at all.

**Comment by gesinn-it-gea** [comment]
@alex-mashin oh, sorry, wrong repo. I'll try to find some time to update the CI process the next days.

**Pull request closed without merging**
