### PR TITLE
Use SMW::SQLStore::AddCustomFixedPropertyTables, refs #48

### PR DESCRIPTION
**Pull request by mwjames**
refs #48

### CODE REVIEW

**Comment by mwjames** [comment]
@kghbln Exception encountered, of type "RuntimeException"

```
Exception encountered, of type "RuntimeException"
[e712e732e5352e6b14d08ce1] /w/index.php?title=Cat%C3%A9gorie:Rechner&oldid=prev&diff=2157 RuntimeException from line 186 of /var/www/htdocs/mw/02100/w/extensions/SemanticMediaWiki/src/MediaWiki/Database.php: A database error has occurred. Did you forget to run maintenance/update.php after upgrading? See: https://www.mediawiki.org/wiki/Manual:Upgrading#Run_the_update_script
Query: SELECT s_id FROM `02100_smw_fpt_sesp_subp` WHERE o_id='2534' LIMIT 1
Function: SMW\SQLStore\QueryEngine\QuerySegmentListProcessor::resolveHierarchyForSegment
Error: 1146 Table '0210020150926.02100_smw_fpt_sesp_subp' doesn't exist (localhost)

```

Could you tell me what table names we have `02100_smw_fpt_sesp_subp` because I think I missed a thing when I switched this.

**Comment by kghbln** [comment]
We have the table `02100_smw_ftp_sesp_subp` but I think it should be at `0210020150926-02100_smw_fpt_sesp_subp` instead of `0210020150926.02100_smw_fpt_sesp_subp`?

**Comment by mwjames** [comment]
> We have the table 02100_smw_ftp_sesp_subp but I think it should be at 0210020150926-02100_smw_fpt_sesp_subp instead of 0210020150926.02100_smw_fpt_sesp_subp?

Well, I thought I missed something after `smw` as in `smw_ftp_sesp_subp` everything before that comes from the DB prefix (nothing from SMW side).

**Comment by kghbln** [comment]
>  that comes from the DB prefix

Affirmative, still wondering why we get the dot instead of the underscore.

**Comment by mwjames** [comment]
Encountered on http://sandbox.semantic-mediawiki.org/w/index.php?title=Cat%C3%A9gorie:Rechner&oldid=prev&diff=2157

**Comment by mwjames** [comment]
> Affirmative, still wondering why we get the dot instead of the underscore.

When we ask MW's `DatabaseBase->select('`02100_smw_fpt_...', 's_id', 'o_id='2534'', ` we only ask for  `02100_smw_fpt_` not sure where the `0210020150926` comes from.

**Comment by kghbln** [comment]
Ah, I just figured it out. There was or is a typo as in `02100_smw_fpt_sesp_subp` as opposed to `02100_smw_ftp_sesp_subp` so now we have two tables for SESP, on with "ftp" and one with "fpt" with the first version as the older one. Which one will it be?

**Comment by mwjames** [comment]
> here was or is a typo as in 02100_smw_fpt_sesp_subp as opposed to 02100_smw_ftp_sesp_subp so now we have two tables for SESP,

Okay, here is the deal before the change we made the table name ourselves `$tableName = 'smw_ftp_sesp' . strtolower( $externalId );`, now only that last bits are added `$customFixedProperties[$externalId] = str_replace( '__', '_', '_sesp' . strtolower( $externalId ) );` and the rest comes from SMW-core.

**Comment by mwjames** [comment]
Shhee ... how do we want to go about this?

**Comment by mwjames** [comment]
... this is pain ... I wanted to get rid of the internal SQLStore dependency in the previous hook and now due to `ftp` vs `fpt` (which means fixed property table), users have to run `rebuildData` and remove the old table.

**Comment by kghbln** [comment]
Hmm, since the SESP release will require running "update.php" followed by "rebuildData.php" in some cases anyway  ("views") some logic may perhaps added to it that deletes the incorrectly named tables. The bigger a wikis is the more likely it is that they want to drop the superfluous tables. We could ask via the mailing list for opinions.

**Comment by kghbln** [comment]
Another follow up error appears when running "rebuildData.php"
```
Running for storage: SMWSQLStore3

Removing table entries (marked for deletion).

.Une erreur de requête de base de données s’est produite.
Requête : DELETE FROM `02100_smw_fpt_sesp_revid` WHERE s_id = '4439'
Fonction : SMW\SQLStore\PropertyTableIdReferenceDisposer::cleanUpTableEntriesFor
Erreur : 1146 Table '0210020150926.02100_smw_fpt_sesp_revid' doesn't exist (localhost)
```

**Comment by mwjames** [comment]
sh..

**Comment by mwjames** [comment]
I suspect that you already deleted those tables `..._smw_fpt_sesp_revid` right?

**Comment by mwjames** [comment]
Never mind, you run `updata.php` and `...smw_fpt_sesp_revid` doesn't exist.

**Comment by kghbln** [comment]
The error message is a bit misleading here: The table exists but not id 4439.

**Comment by mwjames** [comment]
#63 restored previous status quo.

**Comment by kghbln** [comment]
> #63 restored previous status quo.

This is a bit sad since I see the rationale for the change you did.

**Pull request merged**
